### ISSUE TITLE
[FEATURE] Possibility to execute steps in project context

### ISSUE THREAD

**Issue by cumuru** [CPS-IT/project-builder#227]
### Is your feature request related to a problem?

For example package helhum/typo3-console: if you keep track of the console version required for your TYPO3 major version in your config file then you‘re duplicating something that composer can do better.

### Describe the solution you'd like

Add a step/hook which is executed in project context after the templates have been build.

**Comment by mteu** [comment]
Hi @cumuru,

Thanks for your feature request. I've wanted to include such a step anyhow so this great motivation to actually get started on the implementation.

**Comment by mteu** [comment]
The new feature has been merged with https://github.com/CPS-IT/project-builder/pull/228 and will become available with the next release.

**Comment by mteu** [comment]
The new step `runCommand` has been released in `2.3`. Hope it does what you wanted.
