### ISSUE TITLE
[QUESTION] Local Development of templates

### ISSUE THREAD

**Issue by Tim-Obert** [CPS-IT/project-builder#388]
### Is your feature request related to a problem?

Unfortunately, I could not find in the documentation how to integrate the template locally for the creation of a template. 
Do you always have to use a Github repository or similar for development?
For testing, would you then always have to commit and test the change?

### Describe the solution you'd like

It would be cool if you could specify a local path when selecting the template. 

If this is already possible, what needs to be configured for this?

**Comment by mteu** [comment]
Hey @Tim-Obert,

it's admittedly a rather under-documented feature but yes.

It is already possible to work with local templates and multiple Git branches within the `VCS repository` option during the provider selection step at the very beginning.

<img width="759" alt="image" src="https://github.com/CPS-IT/project-builder/assets/2636487/7548a91b-5a1c-4bbb-b65e-738ee98d3f70">

1. When you're prompted for a provider please select: `[2] Try a different provider (e.g. Satis or GitHub)`.
3. Continue with selecting the option `[2] VCS repository  (e.g. GitHub)`. 
4. Put the absolute path to your template folder on your local machine and continue from there.

Hope that helps!

**Comment by Tim-Obert** [comment]
Which Version constraint do I need then if I want to test the local Template?
Currently when I choose "dev-master" the state of the Github-Repository is taken and not the local one.

**Comment by eliashaeussler** [comment]
> Which Version constraint do I need then if I want to test the local Template? Currently when I choose "dev-master" the state of the Github-Repository is taken and not the local one.

Make sure to commit all your local changes, otherwise they won't be respected. There's no need to push them to your remote repository, but it's required to have all changes committed in your local repository. That's because internally Composer runs `git show` on your local files, see https://github.com/composer/composer/blob/2.6.5/src/Composer/Repository/Vcs/GitDriver.php#L154.

**Comment by eliashaeussler** [comment]
@Tim-Obert Can we close this issue? Or do you need additional support for development of your templates? :)

**Comment by Tim-Obert** [comment]
You can close the issue. Thank you for your help!
