### ISSUE TITLE
[TASK] Retire ChangeLog once and for all

### ISSUE THREAD

**Issue by mteu** [CPS-IT/project-builder#70]
### Is your feature request related to a problem?

I, hereby .. officially, question the need for a separete `ChangeLog` file. ♻️ There, I said it. 

### Describe the solution you'd like

I'd like it if we didn't carry the ChangeLog any further.

**Comment by eliashaeussler** [comment]
Hi @mteu, I appreciate your proposal. Let's remove and no longer maintain a `ChangeLog` file.

**Comment by mteu** [comment]
Resolved with #71
